force absolute imports where we can
Implicit relative imports are confusing, as explained in
https://www.python.org/dev/peps/pep-0328/. They have been dropped from
Python 3, too.

Unfortunately, we still use them extensively, but our lib and
vdsm/network directories are almost free of them. This patch drops a
single occurrence and makes sure that we do not happen to add new
implicit relative imports by mistake under thess directories. Future
patches would extend the white list until Vdsm is free of them.

Change-Id: Ibb3aed51c37b846c928fc2d443c9f848dcba5d7c
Signed-off-by: Dan Kenigsberg <danken@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/42045
Reviewed-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>
Reviewed-by: Adam Litke <alitke@redhat.com>
Continuous-Integration: Jenkins CI
Reviewed-by: Nir Soffer <nsoffer@redhat.com>

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -78,6 +78,11 @@ PEP8_BLACKLIST = \
 	vdsm.py \
 	$(NULL)
 
+ABS_IMPORT_WHITELIST = \
+	lib
+	vdsm/network
+	$(NULL)
+
 WHITELIST = \
 	contrib/logdb \
 	contrib/profile-stats \
@@ -104,6 +109,12 @@ gitignore:
 	  done; \
 	fi;
 
+.PHONY: abs_imports
+abs_imports:
+	@for f in `git ls-files $(ABS_IMPORT_WHITELIST) |grep '.py$$\|.py.in$$'`; do\
+	  if ! grep -q '^from __future__ import absolute_import$$' "$$f"; then \
+	    echo "Missing absolute_import in $$f"; exit 1; fi; \
+	done;
 
 SKIP_PYFLAKES_ERR = "\./vdsm/storage/lvm\.py.*: list comprehension redefines \
 	'lv' from line .*"
