net tests: be aware of py3 division
This patch makes sure that existing and future network tests are written
using `/` as a floating point division, and `//` as an integer division,
as required by Python 3. This new requirement is to be extended to all
vdsm files, to ease Python 3 portability.

Change-Id: Ib444e6ef0eee153784169aff4c04c420fd657d3f
Signed-off-by: Dan Kenigsberg <danken@redhat.com>

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -68,6 +68,10 @@ ABS_IMPORT_WHITELIST = \
 	tests \
 	$(NULL)
 
+PY3DIVISION_WHITELIST = \
+	tests/network \
+	$(NULL)
+
 .PHONY: gitignore
 gitignore:
 	@echo "Checking that .in files are ignored..."
@@ -83,6 +87,13 @@ abs_imports: all
 	@for f in `git ls-files $(ABS_IMPORT_WHITELIST) |grep '.py$$'`; do\
 	  if ! grep -q '^from __future__ import absolute_import$$' "$$f"; then \
 	    echo "Missing absolute_import in $$f"; exit 1; fi; \
+	done;
+
+.PHONY: py3division
+py3division: all
+	@for f in `git ls-files $(PY3DIVISION_WHITELIST) |grep '.py$$'`; do\
+	  if ! grep -q '^from __future__ import division$$' "$$f"; then \
+	    echo "Missing __future__.division in $$f"; exit 1; fi; \
 	done;
 
 .PHONY: pylint
@@ -132,7 +143,7 @@ python3: all
 	fi
 
 # Note: dependencies ordered by time needed to run them
-check: gitignore abs_imports imports python3 flake8 pylint tests
+check: gitignore abs_imports py3division imports python3 flake8 pylint tests
 
 check-recursive:
 	@true
