init: add a lock when starting / stopping svdsm
This will prevent a very uncomrfotable situation
where 2 supervdsm processes co-exist at the same time.

*** disclaimer: this patch does not aim to solve 
the bug in the url provided. 
Only aims to avoid the unwanted complication
of 2 supervdsms running at once.

Change-Id: I10bb3f7d39b7dc6a61bce99fab718b51496a37b0
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1254185
Signed-off-by: Yeela Kaplan <ykaplan@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/45202
Continuous-Integration: Dan Kenigsberg <danken@redhat.com>
Reviewed-by: Dima Kuznetsov <dkuznets@redhat.com>
Reviewed-by: Dan Kenigsberg <danken@redhat.com>

diff --git a/init/sysvinit/supervdsmd.init.in b/init/sysvinit/supervdsmd.init.in
--- a/init/sysvinit/supervdsmd.init.in
+++ b/init/sysvinit/supervdsmd.init.in
@@ -70,13 +70,27 @@ stop(){
     return "$RETVAL"
 }
 
+lock_op() {
+    {
+        if ! flock -n 9; then
+            log_failure_msg $"cannot ${1} ${prog}, operation is locked"
+            false
+        elif ( "${1}" 9<&- ); then
+            log_success_msg $"${prog} ${1}"
+        else
+            log_failure_msg $"${prog} ${1}"
+            false
+        fi
+     } 9<$0
+}
+
 case "$1" in
      start)
-        start
+        lock_op start
         RETVAL=$?
         ;;
      stop)
-        stop
+        lock_op stop
         RETVAL=$?
         ;;
      status)
