netwiring: [4/4] Add API definitions.
Fourth and final of the Network Wiring feature patches. It adds the
implementation for using the new vmUpdateDevice feature and add
linkActivate support for createVm and hotplugNic.

Change-Id: I3b9b4f49f80466a83e3e13f1042ac2a8866c6bcd
Signed-off-by: Antoni S. Puimedon <asegurap@redhat.com>
Reviewed-on: http://gerrit.ovirt.org/9562
Reviewed-by: Dan Kenigsberg <danken@redhat.com>
Tested-by: Dan Kenigsberg <danken@redhat.com>

diff --git a/vdsm/vdsmd.init.in b/vdsm/vdsmd.init.in
--- a/vdsm/vdsmd.init.in
+++ b/vdsm/vdsmd.init.in
@@ -463,6 +463,14 @@ start() {
         return $ret_val
     fi
 
+    python @VDSMDIR@/dummybr.pyc
+    ret_val=$?
+    if [ $ret_val -ne 0 ]
+    then
+        log_failure_msg "$prog: Failed to create ephemeral dummy bridge."
+        return $ret_val
+    fi
+
     @VDSMDIR@/vdsm-restore-net-config
     /usr/bin/vdsm-tool load-needed-modules
     mk_data_center
