Define network filter on libvirt
The patch defines custom network filter on libvirt in order to control
the VM traffic. The custom filter is being set when VDSM service is
being started.

Change-Id: I9f1708385dec6a87bc404e4ab25c4da8ab8a8acc
Signed-off-by: Moti Asayag <masayag@redhat.com>
Reviewed-on: http://gerrit.ovirt.org/7354
Reviewed-by: Dan Kenigsberg <danken@redhat.com>
Tested-by: Meni Yakove <myakove@redhat.com>

diff --git a/vdsm/vdsmd.init.in b/vdsm/vdsmd.init.in
--- a/vdsm/vdsmd.init.in
+++ b/vdsm/vdsmd.init.in
@@ -490,6 +490,14 @@ start() {
        return $ret_val
     fi
 
+    @VDSMDIR@/nwfilter.py > /dev/null 2>&1
+    ret_val=$?
+    if [ $ret_val -ne 0 ]
+    then
+        log_failure_msg "$prog: Failed to define network filters on libvirt"
+        return $ret_val
+    fi
+
     @VDSMDIR@/vdsm-restore-net-config
     load_needed_modules
     mk_data_center
