Checking syslog availability before starting vdsm
If logger is not able to open /dev/log, it throws exception and vdsm
does not start. This path verifies that this file exist and fail vdsm
start if not.

Change-Id: I60d0537f67da3cf81477760ccb3760a103dc15ac
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=928861
Signed-off-by: Yaniv Bronhaim <ybronhei@redhat.com>
Reviewed-on: http://gerrit.ovirt.org/13547
Reviewed-by: Dan Kenigsberg <danken@redhat.com>
Reviewed-by: Douglas Schilling Landgraf <dougsland@redhat.com>
Tested-by: Douglas Schilling Landgraf <dougsland@redhat.com>

diff --git a/vdsm/vdsmd.init.in b/vdsm/vdsmd.init.in
--- a/vdsm/vdsmd.init.in
+++ b/vdsm/vdsmd.init.in
@@ -135,6 +135,15 @@ shutdown_conflicting_srv() {
     return 0
 }
 
+syslog_available() {
+    if ! [[ -S "/dev/log" ]]; then
+        log_failure_msg "Cannot communicate with syslog deamon for reports. " \
+                        "Check rsyslog.conf"
+        return 1
+    fi
+    return 0
+}
+
 libvirt_should_use_upstart() {
     [[ -x /sbin/initctl ]]
 }
@@ -456,7 +465,8 @@ start() {
         return $ret_val
     fi
 
-    start_needed_srv && start_libvirtd
+    start_needed_srv && start_libvirtd && syslog_available
+
     ret_val=$?
     if [ $ret_val -ne 0 ]
     then
