BZ#741856 delete rhevm cert before conf_update
Delete CA certificate before updating vdsm-reg.conf, to avoid certificate
collision in the case of later re-configuration with no fingerprint verification

Change-Id: I8bc1dc1fb7fa2ffc0bcb1f6389b34a9ee82b4197
Reviewed-on: http://gerrit.usersys.redhat.com/987
Tested-by: Yotam Oron <yoron@redhat.com>
Reviewed-by: Ayal Baron
Reviewed-by: Dan Kenigsberg <danken@redhat.com>

diff --git a/vdsm_reg/vdsm-config b/vdsm_reg/vdsm-config
--- a/vdsm_reg/vdsm-config
+++ b/vdsm_reg/vdsm-config
@@ -82,6 +82,13 @@ set_addresses() {
 			sed --copy -i "s/\(^vdc_host_name=\)\(..*$\)/\1${vdc_managment_server}/" \
 				/etc/vdsm-reg/vdsm-reg.conf
 
+			res=`python "$DEPLOY_UTIL" --node-cleanup`
+			ret_val=$?
+			echo "$res" >> $LOG 2>&1
+			if [ ! $ret_val -eq 0 ];then
+				echo "Node cleanup failed" >> $LOG 2>&1
+			fi
+
 			if [ "$vdc_managment_server" != "$vdc_managment_port" ]; then
 				sed --copy -i "s/\(^vdc_host_port=\)\(..*$\)/\1${vdc_managment_port}/" \
 					/etc/vdsm-reg/vdsm-reg.conf
